# Logiciels requis pour utiliser et travailler sur les documents du cours Info 114
name: info-114

channels:
- conda-forge

dependencies:
- notebook
- matplotlib
- seaborn
- pandas
- qgrid
- pillow
- scikit-learn
- nbgrader
- nbdime
- jupyter_contrib_nbextensions
#- sqlite==3.28
#- sqlalchemy==1.3.9
- pip
- pip:
# temporarily disabled to avoid conflict with MethNum
#    - "git+https://github.com/nthiery/nbgrader.git@sif"
    - ordo
    - .
    - "git+https://gitlab.u-psud.fr/Info114/Data.git"
