# Logiciels requis pour utiliser et travailler sur les documents du cours Info 114
name: info-114

channels:
- conda-forge

dependencies:
- notebook
- matplotlib
- seaborn
- pandas
- qgrid
- pillow
- scikit-learn
- nbgrader
- nbdime
- jupyter_contrib_nbextensions
- pip
- pip:
    - ordo
    - .
    - "git+https://gitlab.u-psud.fr/Info114/Data.git"
